### ISSUE TITLE
چرا سایت بالا نمیاد؟

### ISSUE THREAD

**Issue by amir1387aht** [vuejs-translations/docs-fa#109]
بچه ها سایت چش شده؟ بالا نمیاد

**Comment by mazdakdev** [comment]
نه، مشکلی نداره.

**Comment by mostafa-nematpour** [comment]
با اینترنت ایران که کلا مشکل داره.
الان که برای من سایت بالا میاد.
سایت هم دست ما نیست، ما فقط repo رو داریم.

**Comment by amir1387aht** [comment]
اره با اینترنت ایران بالا نمیاد ولی جالبیش اینه سایت اصلی با نت ایران میاد بالا اما سایت فارسیی نمیاد
