### ISSUE TITLE
استفاده از فونت های بهینه تر

### ISSUE THREAD

**Issue by Sage-He** [vuejs-translations/docs-fa#201]
استفاده از فونت استعداد به عنوان آخرین همکاری صابر راستیکردار (خالق وزیرمتن) میتونه هم زیبا باشه هم مفید.
درضمن در بخش کامنت های فارسی اگر میتونید بخش های فارسی رو با فونت درست نمایش بده نه با فونت‌های انگلیسی تیز

متشکر بابت زحماتتون

**Comment by mostafa-nematpour** [comment]
سلام، وقتتون بخیر
ممنون بابت معرفی فونت. من تستش کردم و تو نگاه اول خوب بود. ولی بهتر می‌دونم تو گروه از بچه‌ها نظر سنجی کنم.
سعی می‌کنم یه نمونه از سایت با فونت استعداد بالا بیارم و تو گروه نظر سنجی بزارم.

در مورد بخش کامنت‌ها یه چک میکنم ولی احتمال نمیدم بشه درستش کرد چون داره از فونت مربوط به کد استفاده می‌کنه و ممکنه تغییر فونتش به فارسی کد ها رو خراب کنه.

ممنون 🌱

**Comment by Sage-He** [comment]
سلام مجدد. خیلی عالیه. خداقوت
+ میتونید بعد از اولین فونت کد در بخش font-family (معمولا فونت های کد بخش فارسی ندارند) فونت جدید رو قرار بدید، تا بخش های فارسی درست نمایش بدند و کد هم خراب نشه

**Comment by mostafa-nematpour** [comment]
یه آپدیت بدم:
متاسفانه فونت استعداد تو گروه رای نیاورد و فونت سایت همون وزیرمتن می‌مونه.
در مورد بخش کامنت‌ها من متوجه شدم که از فونت فارسی داره استفاده می‌کنه ولی بخاطر طولی که (احتمالا) اسپیس گرفته این شکلی نشون داده می‌شه. به هرحال اگه می‌تونید درستش کنید خوشحال می‌شم که pr بدید یا در ادامه توضیح بیشتر بدید.
ممنون 🌱
