### ISSUE TITLE
یک بخش ترجمه نشده

### ISSUE THREAD

**Issue by Hajibeigloo** [vuejs-translations/docs-fa#215]
توی صفحه 
https://fa.vuejs.org/guide/essentials/computed.html#previous
یک خط متن هست که ترجمه نشده و چیزی هم برای ترجمش به ذهنم نرسید برای همین اومدم بگم که خودتون ترجمه کنید

**Comment by mostafa-nematpour** [comment]
درست شد
ممنون که اطلاع دادی 🌱‎
