### ISSUE TITLE
[Docs] API Page

### ISSUE THREAD

**Issue by mikoloism** [vuejs-translations/docs-fa#74]
سلام، قصد دارم به ترجمه چندی از صفحات `https://fa.vuejs.org/api/` مشارکت داشته باشم، چطوری میتونم متوجه بشم که دوست دیگری به روی این موضوع متمرکز نیست؟

**Comment by the-pesar** [comment]
سلام
توی بخش [روند پیشرفت ترجمه فارسی](https://github.com/vuejs-translations/docs-fa/issues/8) ما هماهنگی‌های لازم برای ترجمه اولیه صفحات رو انجام میدیم.
قبل از شروع [فرایند ترجمه](https://github.com/vuejs-translations/docs-fa/blob/main/README.md) رو هم حتما مطالعه کنید.
موفق باشید.

**Comment by mikoloism** [comment]
ممنون از شما جناب @the-pesar ، بله ایشو رو دیدم...

پس روند به این شکل هست که برای هر صفحه در عوض ایجاد تسک در Issues، به جاش در Tasklist در ایشوی #8 پیش میره؟
به نظر شما بهتر نیست برای تمامی صفحاتی که باید ترجمه بشه یک ایشو جداگانه ایجاد بشه؟
اینجوری در هنگام نوشتن کامیت یا ایجاد PRs با نوشتن شماره issue با علامت هشتگ # اون ایشو به شکل خودکار بسته میشه و به همین ترتیب هماهنگی مشارکت کننده ها هم مشخص‌تر میشه
