### ISSUE TITLE
ترجمه بخش 7 GUIs

### ISSUE THREAD

**Issue by amirofski** [vuejs-translations/docs-fa#92]
سلام. من بخش 7 GUIs شروع کردم

**Comment by the-pesar** [comment]
سلام، عذرخواهی می‌کنم این بخش که محتوایی برای ترجمه نداره!!! دقیقا رو کدوم قسمتش می‌خواین کار کنین؟

**Comment by amirofski** [comment]
من دیدم تیک نداره گفتم. الان دیدم پیچ scaling-up/testing ترجمه نشده و اونو شروع کردم به ترجمه

**Comment by amirofski** [comment]
ببخشید اشتباه از من بود.  بخش examples/#counter شروع کردم

**Comment by the-pesar** [comment]
صفحه رو بهتون اختصاص دادم. لطفا دفعات بعد توی[ گروه تلگرام](https://t.me/Vue_Docs_Fa) یا این [issue](#8) اعلام کنید.
موفق باشید.
